- packages/graphic-walker/package.json
- packages/graphic-walker/src/models/visSpecHistory.ts
`@kanaries/graphic-walker = 0.2.15`
**Fix**: 0.2.15 -> **0.2.16 ↑**
Method `VisSpecWithHistory.clone()` brought an issue:
The copied instance has a cursor to be the same value as the source instance, however the list of snapshots was not synchronized. Accessing the current frame will get an `undefined`.
https://graphic-walker-gssrfazjk-kanaries.vercel.app/
* Edit a chart (make the length of snapshots > 1), edit its name.
* Or, let there be only one chart, edit it (make the length of snapshots > 1), switch to the **Data** tab, and then switch back to the **Visualization** tab.
_I used `JSON.parse(JSON.stringify())` to generate a deep copy in the log so actually the snapshot list was `[<object> x m, empty x n]`, while the cursor is `m + n`, partially updated._ …
> fix: chart history cursor overflow

- packages/graphic-walker/src/fields/encodeFields/singleEncodeEditor.tsx
Aggregation menu in the signleEncodeEditor disappeared because of the overflow.
> fix(singleEncodeEditor): aggr menu disappeared

- packages/graphic-walker/package.json
- packages/graphic-walker/src/App.tsx
- packages/graphic-walker/src/locales/en-US.json
- packages/graphic-walker/src/locales/ja-JP.json
- packages/graphic-walker/src/locales/zh-CN.json
- packages/graphic-walker/src/visualSettings/index.tsx
A new optional `toolbar` prop can be set to
1. add custom toolbar items,
2. hide default toolbar items.
Developers could use this prop to modify items of the toolbar to insert their own controls - instead of creating a patch and develop changes to GraphicWalker package.
> feat(): customize toolbar settings

- packages/graphic-walker/src/components/appRoot.tsx
- packages/graphic-walker/src/index.tsx
- packages/graphic-walker/src/interfaces.ts
- packages/graphic-walker/src/renderer/hooks.ts
- packages/graphic-walker/src/renderer/index.tsx
- packages/graphic-walker/src/renderer/pureRenderer.tsx
- packages/graphic-walker/src/utils/chartIndexControl.ts
- packages/graphic-walker/src/utils/vegaApiExport.ts
- packages/graphic-walker/src/vis/react-vega.tsx
No breaking changes.
The fields with docs are those added in this PR.
```typescript
interface IGWHandler {
/** length of the "chart" tab list */
chartCount: number;
/** current selected chart index */
chartIndex: number;
/** Switches to the specified chart */
openChart: (index: number) => void;
/**
* Returns the status of the current chart.
* 
* It is computed by the following rules:
* - If _GraphicWalker_ is computing the data view, it returns `computing`.
* - If _GraphicWalker_ is rendering the chart, it returns `rendering`.
* - If rendering is finished, it returns `idle`.
* - If an error occurs during the process above, it returns `error`.
*/
get renderStatus(): IRenderStatus;
/**
* Registers a callback function to listen to the status change of the current chart.
* 
* @param …
```
> [Feat] gw ref update

- packages/graphic-walker/src/interfaces.ts
- packages/graphic-walker/src/store/visualSpecStore.ts
- packages/graphic-walker/src/utils/save.ts
This fix ensures that Sets in `filters` are encoded as Arrays when exporting data and vice versa when importing data.
> fix: bug in vis spec export #97

- packages/graphic-walker/src/components/limitSetting.tsx
- packages/graphic-walker/src/components/sizeSetting.tsx
- packages/graphic-walker/src/hooks/index.ts
- packages/graphic-walker/src/renderer/hooks.ts
- packages/graphic-walker/src/store/visualSpecStore.ts
- packages/graphic-walker/src/visualSettings/index.tsx
This commit reduce unnecessary calc when editing limit and chart size.
> fix: reduce freq of setVisualConfigs

- packages/graphic-walker/src/renderer/index.tsx
When creating new chart, dataQueryServer returns immediately so 'waiting' won't change when render function executes.
Added 'data' to dependency to make sure to setViewData.
> fix: graph didn't disappear when changing tab

- packages/graphic-walker/src/components/pivotTable/index.tsx
> fix: add title in pivot table

- packages/graphic-walker/src/components/visualConfig/colorScheme.tsx
- packages/graphic-walker/src/components/visualConfig/index.tsx
- packages/graphic-walker/src/locales/en-US.json
- packages/graphic-walker/src/locales/ja-JP.json
- packages/graphic-walker/src/locales/zh-CN.json
- packages/graphic-walker/src/utils/save.ts
By design, the user set custom color settings will override themeConfig.
This pr removes the default set color setting to make color in themeConfig available.
> fix: remove initial primary color

- packages/graphic-walker/src/computation/serverComputation.ts
- packages/graphic-walker/src/fields/filterField/tabs.tsx
- packages/graphic-walker/src/lib/inferMeta.ts
- packages/graphic-walker/src/lib/interfaces.ts
- packages/graphic-walker/src/lib/op/aggregate.ts
fixes #181 .
change the method to get temporal range from "get first 1000 lines of values, and calc max & min" to "require computation to return a max/min value of temporal".
Notice: The Computation Function should be compatible with workflow like:
```
{
op: 'aggregate',
groupBy: [],
measures: [{ field: "datetime", agg: 'min', asFieldKey: 'MIN', format: '%Y-%m-%d %H:%M:%S' }],
}
```
> feat: change temporal range

- packages/graphic-walker/src/index.tsx
- packages/graphic-walker/src/renderer/pureRenderer.tsx
- packages/graphic-walker/src/store/dataStore.ts
- packages/graphic-walker/src/store/visualSpecStore.ts
- packages/graphic-walker/src/utils/save.ts
replace "importOld" method to "importCode", so you can use this function to initial visStore and don't have to care what is version of visSpec.
> fix: make eaiser to import old format data

- packages/graphic-walker/src/components/pivotTable/index.tsx
- packages/graphic-walker/src/components/pivotTable/inteface.ts
- packages/graphic-walker/src/components/pivotTable/utils.ts
- packages/graphic-walker/src/services.ts
- packages/graphic-walker/src/store/visualSpecStore.ts
- packages/graphic-walker/src/workers/buildMetricTable.worker.js
- packages/graphic-walker/src/workers/buildPivotTable.ts
Make data in pivot table is sortable.
sorting: sort the last field without measure field.
sort by nearest value in same group.
collpase won't affect sorting.
e.g.
original: 
sorted by asc:
with empty field:
original: 
sorted by dsc:
> feat: pivot sorting

- packages/graphic-walker/src/components/timeoutImg.tsx
fix the problem that TimeoutImg always use fallback image.
> fix: timeout img not working

- packages/graphic-walker/src/App.tsx
- packages/graphic-walker/src/components/errorpanel/index.tsx
- packages/graphic-walker/src/store/index.tsx
- packages/graphic-walker/src/store/visualSpecStore.ts
- packages/graphic-walker/src/utils/index.ts
- packages/graphic-walker/src/utils/reportError.ts
When computation function has error, graphic walker will show a modal instead of just show a message in the log.
> fix: add report compuation error

- packages/graphic-walker/src/components/pivotTable/index.tsx
- packages/graphic-walker/src/store/visualSpecStore.ts
- packages/graphic-walker/src/utils/index.ts
Fix js error `Cannot read properties of null` when use PureRenderer with visualConfig.geoms = []。
> fix: pivot table cause Error in pure renderer

- packages/graphic-walker/src/App.tsx
- packages/graphic-walker/src/components/clickMenu.tsx
- packages/graphic-walker/src/components/embedMenu.tsx
- packages/graphic-walker/src/config.ts
- packages/graphic-walker/src/interfaces.ts
- packages/graphic-walker/src/renderer/index.tsx
add control of VizEmbedMenu in GLBOAL_CONFIG for user to disable it.
usage:
```
import { getGlobalConfig } from "@kanaries/graphic-walker";
getGlobalConfig().EMBEDED_MENU_LIST = [];
```
> chore: control VizEmbedMenu in GLBOAL_CONFIG

- computation.md
> doc: typo fix

- packages/graphic-walker/src/components/dataTable/index.tsx
- packages/graphic-walker/src/components/modal.tsx
- packages/graphic-walker/src/components/smallModal.tsx
- packages/graphic-walker/src/computation/clientComputation.ts
- packages/graphic-walker/src/computation/index.ts
- packages/graphic-walker/src/dataSource/datasetConfig/index.tsx
- packages/graphic-walker/src/dataSource/table.tsx
- packages/graphic-walker/src/fields/filterField/filterEditDialog.tsx
- packages/graphic-walker/src/lib/sort.ts
Add Filter and sorting to DataTable.
Filter: 
Press Filter button on Table header to create a Filter.
When using Filter, the Filters of DataTable will show on the top of the table.
Click Tag to Open EditDialog, and Click Remove Button to Remove the Filter.
If add a Filter is causing showing bounds out of the total data, the page will be reset to 1.
Sorting:
Press on Header text will add a descending sort on this header.
Press it again will make sort to be ascending.
> feat: add Sorting & Filter for DataTable

- packages/graphic-walker/src/App.tsx
- packages/graphic-walker/src/FullApp.tsx
- packages/graphic-walker/src/Table.tsx
- packages/graphic-walker/src/components/dataTable/index.tsx
- packages/graphic-walker/src/components/filterWalker/index.tsx
- packages/graphic-walker/src/index.tsx
- packages/graphic-walker/src/interfaces.ts
- packages/graphic-walker/src/vanilla.tsx
Add a new Component TableWalker to use Table as a Component.
usage: 
```
import { TableWalker } from "@kanaries/graphic-walker";
// use static data
<TableWalker dataSource={data} rawFields={meta} />
// use a custom computation
<TableWalker computation={computation} rawFields={meta} />
```
> Feat: export table as Component

- packages/graphic-walker/src/renderer/pureRenderer.tsx
- packages/graphic-walker/src/renderer/specRenderer.tsx
fix an issue when rendering Chart with size=auto in Purerenderer, the actual element size will equal the hidden property "width" and "height" and the chart's can overflow the container element.
> fix: pure-renderer size

- packages/graphic-walker/src/fields/filterField/tabs.tsx
- packages/graphic-walker/src/lib/op/dateTimeDrill.ts
- packages/graphic-walker/src/utils/index.ts
Fixed issue when saved a Temporal Filter, and open it again, the value will shift some hours that effected by locale timezone.
error screenshot:
except behaivor:
> fix: fix date picker with timezone

- packages/graphic-walker/package.json
- packages/graphic-walker/src/components/modal.tsx
- packages/graphic-walker/src/components/smallModal.tsx
- packages/graphic-walker/src/fields/datasetFields/dimFields.tsx
- packages/graphic-walker/src/fields/datasetFields/meaFields.tsx
- packages/graphic-walker/src/fields/encodeFields/singleEncodeEditor.tsx
- packages/graphic-walker/src/fields/fieldsContext.tsx
- packages/graphic-walker/src/fields/filterField/filterPill.tsx
- packages/graphic-walker/src/fields/filterField/index.tsx
- packages/graphic-walker/src/fields/obComponents/obFContainer.tsx
- packages/graphic-walker/src/fields/obComponents/obPill.tsx
- packages/graphic-walker/src/utils/proxy.ts
- yarn.lock
Make graphic-walker's drag'n'drop usable in some containing block context
Test: 
add code above to graphic-waklker container
```
<div id="root" style="
height: 200vh;
"><div style="
position: fixed;
top: 80px;
bottom: 80px;
left: 80px;
right: 80px;
padding: 20px;
border: 1px solid black;
overflow: auto;
">
(GraphicWalker)
</div></div>
```
> fix: dnd issue in containing block

- computation.md
- packages/graphic-walker/package.json
- packages/graphic-walker/src/computation/clientComputation.ts
- packages/graphic-walker/src/computation/index.ts
- packages/graphic-walker/src/fields/filterField/filterPill.tsx
- packages/graphic-walker/src/fields/filterField/tabs.tsx
- packages/graphic-walker/src/interfaces.ts
- packages/graphic-walker/src/lib/filter.ts
- packages/graphic-walker/src/lib/op/aggregate.ts
- packages/graphic-walker/src/lib/op/stat.ts
- packages/graphic-walker/src/utils/filter.ts
- packages/graphic-walker/src/utils/workflow.ts
- yarn.lock
make the list in FilterEditDialog become a VirtualList
and it will fetch only data in view, reduce the cost of running on large dataset.
also introduced a new type of filter, 'not in', to make it possible save a filter without fetching all data.
> feat: filter Edit dialog optimize

- packages/graphic-walker/src/fields/filterField/filterEditDialog.tsx
- packages/graphic-walker/src/fields/filterField/filterPill.tsx
- packages/graphic-walker/src/fields/filterField/tabs.tsx
- packages/graphic-walker/src/hooks/index.ts
- packages/graphic-walker/src/interfaces.ts
- packages/graphic-walker/src/locales/en-US.json
- packages/graphic-walker/src/locales/ja-JP.json
- packages/graphic-walker/src/locales/zh-CN.json
- packages/graphic-walker/src/models/visSpecHistory.ts
- packages/graphic-walker/src/store/visualSpecStore.ts
- packages/graphic-walker/src/utils/index.ts
- packages/graphic-walker/src/utils/workflow.ts
This PR relies on DSL parser to support get info of a aggregated view.
Add a aggregation dropdown in FilterDialog when the field is measure.
the range that can be set will relies on the Group in current Vis.
When there is no group set, the range in dialog will be stat of the original field even the aggregation is 'count'.
and the aggregation filter will be ignored when there is no group set, or it's not aggregated chart.
> feat: use Filter with aggregation

- packages/graphic-walker/src/components/visualConfig/index.tsx
- packages/graphic-walker/src/lib/gog.ts
- packages/graphic-walker/src/models/visSpecHistory.ts
- packages/graphic-walker/src/store/visualSpecStore.ts
issue: when draging MeasureValues, MeasureName, Row count from encodings to field list, will do nothing instead of removing fields.
fixed this
update: add a lint make the MeasureValues MeasureName & RowCount field at fixed positon in meta.
> fix: dragging count field to left side is broken

- packages/graphic-walker/src/App.tsx
- packages/graphic-walker/src/renderer/specRenderer.tsx
Fixed the issue when chart size is "auto" and it exceed the graphic-walker container width, the chart will overflow the container instead of show a scrollbar.
> fix: graphic walker chart scroll

- packages/graphic-walker/src/computation/index.ts
- packages/graphic-walker/src/fields/filterField/tabs.tsx
change the distinctCount logic to use double views, to contains when field containing NULL fields in SQL backend.
fixed select all not reponsive at some situation.
bug screenshot: 
fixed:
> chore: change distinct count logic

- packages/graphic-walker/src/components/callout.tsx
- packages/graphic-walker/src/components/limitSetting.tsx
- packages/graphic-walker/src/components/sizeSetting.tsx
- packages/graphic-walker/src/components/tooltip.tsx
Kanaries is an awesome tool for data visual analysis, though I've encountered some UI details concerning the 'Tooltip' and 'Callout' that could be improved.
| Before | After |
| -------- | -------- | 
| <img width="782" alt="image" src="https://github.com/Kanaries/graphic-walker/assets/125171539/f06781f7-4b1b-41c5-9133-4575c2112fab"> | <img width="833" alt="image" src="https://github.com/Kanaries/graphic-walker/assets/125171539/96958441-390c-46fb-bc96-afd474e6ec9d"> |
| Before | After |
| -------- | -------- | 
| <img width="842" alt="image" src="https://github.com/Kanaries/graphic-walker/assets/125171539/103e77ca-e2e0-4876-90a0-ad895aa53553"> | <img width="855" alt="image" src="https://github.com/Kanaries/graphic-walker/assets/125171539/54cad0b1-0e5c-4f01-bd09-e0d3b59d9dee"> |
| <img …
> feat: enhance font style for `Tooltip` and `Callout`

- packages/graphic-walker/src/dataSource/config.ts
- packages/graphic-walker/src/dataSource/dataSelection/publicData.tsx
Users now receive immediate feedback and reduce confusion when selecting datasets.
https://github.com/Kanaries/graphic-walker/assets/125171539/8b1edaec-21ff-4792-9be5-4663e6a808cc
https://github.com/Kanaries/graphic-walker/assets/125171539/5db7a49c-d59a-4f1b-b7e4-6e548aec2fb9
> feat: improve interaction of Public Datasets selector

- packages/graphic-walker/src/visualSettings/index.tsx
- packages/graphic-walker/src/visualSettings/utils.test.ts
- packages/graphic-walker/src/visualSettings/utils.ts
At the current, using `toolbar.exclude` prop sometimes make some UI problems.
1. heading/trailing separator: ex. if `kanaries` is excluded, the separator appears at the end of toolbar.
2. consecutive separators: ex. if `coord_system` is excluded, consecutive separators appears at the middle of toolbar.
This pull request will cause leading and trailing separators and consecutive separators to be removed.
> feat: omit redundant separators

- packages/graphic-walker/src/models/visSpecHistory.ts
change default fold value to first measure, to make it easier to use when there is lots of measure fields.
> chore: change default fold value

- packages/graphic-walker/src/computation/index.ts
- packages/graphic-walker/src/fields/filterField/slider.tsx
when setting only a filter, the graphic walker will query a empty view query, which would cause error when using computation function.
this PR fixed this and blocked the query in this situation.
> fix: block empty view workflow

- packages/graphic-walker/src/App.tsx
- packages/graphic-walker/src/Table.tsx
Currently, the Error Panel only shows in Vis Segment, and will show nothing when user is in Data Segment even there is error when Table component fetching data.
This PR let it shows when DataTable meets Errors too.
> fix: add error panel for table

- packages/graphic-walker/package.json
- packages/graphic-walker/src/App.tsx
- packages/graphic-walker/src/config.ts
- packages/graphic-walker/src/interfaces.ts
- packages/graphic-walker/src/lib/vega.ts
- packages/graphic-walker/src/locales/en-US.json
- packages/graphic-walker/src/locales/ja-JP.json
- packages/graphic-walker/src/locales/zh-CN.json
- packages/graphic-walker/src/models/visSpecHistory.ts
- packages/graphic-walker/src/renderer/pureRenderer.tsx
- packages/graphic-walker/src/renderer/specRenderer.tsx
- packages/graphic-walker/src/vis/react-vega.tsx
- yarn.lock
this PR includes a new size mode, 'container'
in this mode, the chart will fill to the container size
Add a new prop for PureRenderer to override size easily, useful for using in card.
`<PureRenderer
{...props}
overrideSize={{mode : 'full', width: 1, height: 1}}
/>`
> Feat: Add new size mode `container`

- packages/graphic-walker/src/components/painter/components.tsx
- packages/graphic-walker/src/components/painter/index.tsx
- packages/graphic-walker/src/interfaces.ts
- packages/graphic-walker/src/lib/execExp.ts
- packages/graphic-walker/src/lib/paint.ts
- packages/graphic-walker/src/locales/en-US.json
- packages/graphic-walker/src/locales/ja-JP.json
- packages/graphic-walker/src/locales/zh-CN.json
- packages/graphic-walker/src/models/visSpecHistory.ts
- packages/graphic-walker/src/store/visualSpecStore.ts
- packages/graphic-walker/src/utils/workflow.ts
- packages/graphic-walker/src/vis/spec/encode.ts
- packages/graphic-walker/src/visualSettings/index.tsx
Add support for nominal fields and ordinal fields in data painter.
Temproal fields is not support now.
> feat: add nominal support for data painter

- packages/graphic-walker/src/App.tsx
- packages/graphic-walker/src/Table.tsx
- packages/graphic-walker/src/interfaces.ts
- packages/graphic-walker/src/models/visSpecHistory.ts
- packages/graphic-walker/src/store/index.tsx
- packages/graphic-walker/src/store/visualSpecStore.ts
- packages/graphic-walker/src/utils/workflow.ts
Added a new prop: defaultConfig.
usage: 
`<GraphicWalker defaultConfig={{ config: { timezoneDisplayOffset: 0 }, layout: { size: { mode: 'full', width: 100, height: 100 } } }}></GraphicWalker>`
so developer can provide some config for user to have as default.
> feat: add default config for configuing timezone offset

- packages/graphic-walker/src/fields/aestheticFields.tsx
- packages/graphic-walker/src/fields/encodeFields/multiEncodeEditor.tsx
This PR allows the details channel to display multiple fields within it, instead of hiding them as before.
> feat: use multi encode editor for detail

- packages/graphic-walker/src/dataSource/dataSelection/csvData.tsx
- packages/graphic-walker/src/dataSource/index.tsx
- packages/graphic-walker/src/vanilla.tsx
add dark mode for datasource segement
> fix: darksource segment darkmode

- packages/graphic-walker/src/fields/components.tsx
fixed the contrast of badge border in X-Y axis.
> fix: lighten OBPill's border color

- packages/graphic-walker/src/App.tsx
- packages/graphic-walker/src/renderer/specRenderer.tsx
This PR changes the loading to extend full container.
in PureRenderer:
In GraphicWalker:
> chore: loading style

- README.md
- packages/graphic-walker/src/dataSourceProvider/localStorage.ts
- packages/graphic-walker/src/dataSourceProvider/memory.ts
- packages/graphic-walker/src/renderer/pureRenderer.tsx
- packages/graphic-walker/src/vanilla.tsx
- packages/playground/src/examples/nav.tsx
- packages/playground/src/examples/pages/cc.stories.tsx
- packages/playground/src/examples/pages/ds.stories.tsx
- packages/playground/src/examples/pages/inModal.stories.tsx
- packages/playground/src/examples/pages/table.stories.tsx
- packages/playground/src/examples/pages/table.tsx
Add the TableWalker component page and its introduction in readme.md
> chore: add examples for tablewalker component

- packages/graphic-walker/src/vis/react-vega.tsx
Fixes the issue that when using container size mode and a faceted view, the size is incorrect and the color legend will be hidden.
> fix: facet view container size

- packages/graphic-walker/src/lib/vega.ts
- packages/graphic-walker/src/vis/spec/view.ts
This PR fixes the color legend issue in repeated view.
before: 
fixed:
> fix: color legend issue with repeated view

- packages/graphic-walker/src/components/computedField/index.tsx
- packages/graphic-walker/src/store/visualSpecStore.ts
fixed the issue when there is field that named as "dark", "className", "div", ...etc, and the computed field editor will be broken.
> fix: sql field highlight replace order

- packages/graphic-walker/src/components/dataBoard.tsx
Fixed the issue that when click "DataView" in a filtered chart, the data in dialog will contains data that not filtered.
> fix: add filter in data board

- packages/duckdb-wasm-computation/package.json
- packages/graphic-walker/package.json
- packages/graphic-walker/tsconfig.json
- yarn.lock
This PR changes the output of graphic-walker's build, and make users can import minimal items from graphic walkers by codes like:
```
import { chartToWorkflow } from '@kanaries/graphic-walker/utils/workflow';
```
> chore: change emit contents

- packages/graphic-walker/src/components/dataTable/index.tsx
- packages/graphic-walker/src/fields/datasetFields/dimFields.tsx
- packages/graphic-walker/src/fields/datasetFields/meaFields.tsx
- packages/graphic-walker/src/fields/encodeFields/multiEncodeEditor.tsx
- packages/graphic-walker/src/fields/encodeFields/singleEncodeEditor.tsx
- packages/graphic-walker/src/fields/filterField/index.tsx
- packages/graphic-walker/src/fields/obComponents/obFContainer.tsx
- packages/graphic-walker/src/interfaces.ts
- packages/graphic-walker/src/lib/op/fold.ts
- packages/graphic-walker/src/lib/vl2gw.ts
- packages/graphic-walker/src/models/visSpecHistory.ts
- packages/graphic-walker/src/renderer/hooks.ts
- packages/graphic-walker/src/store/visualSpecStore.ts
- packages/graphic-walker/src/utils/index.ts
- packages/graphic-walker/src/utils/workflow.ts
- packages/graphic-walker/src/vis/spec/field.ts
The dragId field in the graphic walker spec is redundant, and had caused many dragging issue.
This PR removed dragId from the specs, used a method to generate a unique dragId in component, to avoid bugs casued by duplicate dragId in spec.
> Remove dragId from specs

- packages/graphic-walker/src/components/leafletRenderer/ChoroplethRenderer.tsx
- packages/graphic-walker/src/components/leafletRenderer/index.tsx
- packages/graphic-walker/src/components/visualConfig/index.tsx
- packages/graphic-walker/src/interfaces.ts
This PR add a config to show all shapes in provided geoshape data, and will show them without data in a 0.3 opacity.
> feat: add option to show all geoshapes

- packages/graphic-walker/src/vis/react-vega.tsx
fixed a issue when using auto layout & facet view, the charts will be spaced between each other.
problem screenshot:
fixed:
> fix: auto facet layout

- packages/graphic-walker/src/fields/encodeFields/multiEncodeEditor.tsx
- packages/graphic-walker/src/fields/encodeFields/singleEncodeEditor.tsx
- packages/graphic-walker/src/fields/filterField/index.tsx
- packages/graphic-walker/src/fields/obComponents/obFContainer.tsx
- packages/graphic-walker/src/lib/op/aggregate.ts
fixed a drag issue when dragging same field into same channel, there will be drag issue with theme because of same dragId.
> Fix drag issue when contains same field

- packages/graphic-walker/src/App.tsx
- packages/graphic-walker/src/interfaces.ts
add a new prop: hideChartNav to hide the chart navigation.
usage: 
```
<GraphicWalker {...props} hideChartNav />
```
> feat: add hide-nav config for web use

- packages/graphic-walker/src/Table.tsx
- packages/graphic-walker/src/store/visualSpecStore.ts
Make TableWalker able to change field's meta when the onMetaChange prop is set in TableWalker.
> feat: add meta change feature for TableWalker

- packages/graphic-walker/src/lib/vega.ts
- packages/graphic-walker/src/renderer/specRenderer.tsx
- packages/graphic-walker/src/vis/react-vega.tsx
This PR make user can change the chart size by dragging when using facet chart.
> chore: ability to change facet chart fixed size

- packages/graphic-walker/src/lib/vega.ts
- packages/graphic-walker/src/vis/react-vega.tsx
fix the issue that chart cannot render when repeat with null x-axis or y-axis.
> fix: repeat with null

- packages/graphic-walker/src/vis/react-vega.tsx
Fixed a issue when using auto layout and color encoding and repeating field, there will be a gap that width equals to color panel.
> fix: width issue when using color and repeat

- packages/graphic-walker/src/components/pivotTable/index.tsx
- packages/graphic-walker/src/components/pivotTable/leftTree.tsx
- packages/graphic-walker/src/components/pivotTable/topTree.tsx
fix the date show in pivot table
> fix: pivot table date format

- packages/graphic-walker/src/components/ui/toggle.tsx
- packages/graphic-walker/src/lib/vl2gw.ts
This PR changed the toggled button's color.
> chore: change toggle color of toolbar to improve visibility

- .github/workflows/bump-version.yml
- .github/workflows/release-duckdb.yml
- packages/duckdb-wasm-computation/package.json
- packages/duckdb-wasm-computation/src/index.ts
- packages/duckdb-wasm-computation/tsconfig.json
- yarn.lock
add a action to publish duckdb module.
> feat: publish duckdb module

- packages/graphic-walker/package.json
- packages/graphic-walker/src/components/dataTable/index.tsx
- packages/graphic-walker/src/components/dataTable/profiling.tsx
- packages/graphic-walker/src/components/ui/hover-card.tsx
- yarn.lock
Apply max width on DataTable cells.
When a cell is truncated, hover it will display a hover card and user can copy the value of the cell in the card.
> feat: add max width for table cells

- packages/graphic-walker/src/components/pivotTable/index.tsx
- packages/graphic-walker/src/components/pivotTable/utils.ts
This PR fixed a bug that caused by a dependency is missed so the table summary feature cannot reactive immediately.
> fix: show table summary is not reactive in pivot table

- packages/graphic-walker/src/components/limitSetting.tsx
- packages/graphic-walker/src/locales/en-US.json
- packages/graphic-walker/src/locales/ja-JP.json
- packages/graphic-walker/src/locales/zh-CN.json
The limit value is a very precise value, and it is not so simple to adjust the limit using a slider.
So I think it might be simpler to allow users to enter the value directly.
> feat: modify ui of limit tool

- packages/graphic-walker/scripts/create-json-schema.js
- packages/graphic-walker/src/App.tsx
- packages/graphic-walker/src/components/pivotTable/index.tsx
- packages/graphic-walker/src/models/visSpec.ts
- packages/graphic-walker/src/renderer/pureRenderer.tsx
- packages/graphic-walker/src/renderer/specRenderer.tsx
- packages/graphic-walker/src/store/storeStateLib.ts
- packages/graphic-walker/src/store/visualSpecStore.ts
- yarn.lock
Fixed the error when using purerenderer with a pivot table chart, the component will crash and throw a `Cannot read properties of undefined (reading 'timezoneDisplayOffset')`.
> fix: error when pureRenderer displaying pivot table

- packages/graphic-walker/src/components/codeExport/index.tsx
Added a workflow tab to show workflow of current chart.
> chore: add workflow tab in export

- packages/graphic-walker/src/components/dataTable/profiling.tsx
- packages/graphic-walker/src/computation/index.ts
- packages/graphic-walker/src/interfaces.ts
Since profiling is a feature that consumes a lot of computing resources.
The field is needed to identify profiling when performing computing, and base on this field to make some additional operations (such as caching).
> feat: add tag flag in profiling computation

- packages/graphic-walker/src/Table.tsx
- packages/graphic-walker/src/components/dataTable/index.tsx
- packages/graphic-walker/src/index.css
- packages/graphic-walker/src/interfaces.ts
- packages/graphic-walker/src/renderer/pureRenderer.tsx
- packages/graphic-walker/src/root.tsx
- packages/playground/src/examples/pages/inModal.stories.tsx
- packages/playground/src/examples/pages/renderer.tsx
Imporove the apperence when datatable is embed into a small container
> chore: imporove dataTable when embed

- packages/graphic-walker/src/Table.tsx
- packages/graphic-walker/src/components/dataTable/index.tsx
- packages/graphic-walker/src/interfaces.ts
- packages/playground/src/examples/pages/table.stories.tsx
Added tableFilterRef prop for TableWalker.
Added a example for using tableFilterRef to export csv with filters.
> feat: add table filter ref and example

- packages/graphic-walker/src/components/toolbar/index.tsx
fixed the issue when the width of graphic walker is between 640px and 900px, the width isn't enough to show all buttons in the toolbar.
This PR set the query into 1024px so the toolbar can show completely.
> fix: let the toolbar wrap in lg screen

- packages/graphic-walker/src/components/leafletRenderer/geoConfigPanel.tsx
- packages/graphic-walker/src/main.tsx
- packages/playground/src/main.tsx
1. fixed the geoKey won't be saved when geoData not set.
2. change the default World Countries data.
3. added the preview when selecting preset geo data.
> fix: geo panel issue

- packages/graphic-walker/src/vis/react-vega.tsx
fix a issue that cause the re-rendering is called when dragging the fixed chart size.
> fix: fixed size change

- packages/graphic-walker/jest.config.js
- packages/graphic-walker/src/components/dataTable/pagination.test.ts
- packages/graphic-walker/src/components/dataTable/pagination.tsx
fixed the pagination button appearence when there are many pages.
> fix: dataTable pagination

- packages/graphic-walker/src/components/askViz/index.tsx
- packages/graphic-walker/src/components/chat/index.tsx
- packages/graphic-walker/src/components/painter/components.tsx
- packages/graphic-walker/src/fields/filterField/slider.tsx
fix a issue, when using ime with input, press enter will make the content in input to perform a action.
> feat: input enter with ime

- packages/graphic-walker/src/lib/op/dateTimeDrill.ts
- packages/graphic-walker/src/lib/op/dateTimeFeature.ts
- packages/graphic-walker/src/lib/op/offset.ts
- packages/graphic-walker/src/utils/index.ts
- packages/graphic-walker/src/vis/spec/view.ts
make the table and chart can deal with null temporal values, not showing 1970-1-1.
non-null value will still show on the chart, and null temporal value will not be shown in the chart.
> fix: null value of temporal

- packages/graphic-walker/src/dataSource/dataSelection/csvData.tsx
- detect .csv or .json by filename when uploading dataset
- remove manual file type chooser
- `yarn workspace @kanaries/graphic-walker test` *(fails: package doesn't seem to be present in lockfile)*
> Auto detect dataset file type

- packages/playground/src/examples/nav.tsx
- packages/playground/src/examples/pages/exportChart.stories.tsx
- packages/playground/src/examples/pages/exportChart.tsx
- showcase downloading chart images via the export API
- `npm run lint` in `packages/playground`
- `npm test` in `packages/graphic-walker`
> Add export chart example

- packages/graphic-walker/src/components/painter/index.tsx
- packages/graphic-walker/src/store/visualSpecStore.ts
- packages/graphic-walker/src/utils/vegaApiExport.ts
fix the issue when editing the paintMap with same dimensions but tranversed, the map will not be loaded and user cannot see correct result in the page.
> fix: paint info
