packages/graphic-walker/src/config.ts, packages/graphic-walker/src/interfaces.ts, packages/graphic-walker/src/locales/en-US.json, packages/graphic-walker/src/locales/zh-CN.json, packages/graphic-walker/src/renderer/index.tsx, packages/graphic-walker/src/store/visualSpecStore.ts, packages/graphic-walker/src/utils/save.ts, packages/graphic-walker/src/vis/react-vega.tsx, packages/graphic-walker/src/visualSettings/index.tsx
* **Cross Filters**
Brushing and Pointing interactions applied to create filters across sub-charts are supported as configurable settings. _As a side effect, Data Interpreting is now enabled ONLY WHEN this feature is toggled OFF._
=> Feat: Cross Filters in GraphicWalker

packages/graphic-walker/package.json, packages/graphic-walker/src/App.tsx, packages/graphic-walker/src/locales/en-US.json, packages/graphic-walker/src/locales/zh-CN.json, packages/graphic-walker/src/renderer/index.tsx, packages/graphic-walker/src/vis/react-vega.tsx, packages/graphic-walker/src/visualSettings/index.tsx
✅ Download the charts using a button.
_This feature is implemented by [another PR](https://github.com/Kanaries/Rath/pull/239) either._
=> [feat] {gw} download charts as png or svg

packages/graphic-walker/src/interfaces.ts, packages/graphic-walker/src/renderer/specRenderer.tsx, packages/graphic-walker/src/store/visualSpecStore.ts, packages/graphic-walker/src/vis/react-vega.tsx, packages/graphic-walker/src/vis/spec/view.ts, packages/graphic-walker/src/visualSettings/index.tsx
Changes:
* Remove a store member controlling the brush mode, and the corresponding control in the toolbar.
* Remove unreachable code in the render (encoding) method.
=> feat(crossFilter): remove brush settings and state

packages/graphic-walker/src/interfaces.ts, packages/graphic-walker/src/store/visualSpecStore.ts, packages/graphic-walker/src/utils/index.ts, packages/graphic-walker/src/workers/transform.ts
Fixed the other references this time :) 
申し訳ありません 
お疲れ様!!
=> Fixing a typo

packages/graphic-walker/src/vis/spec/tooltip.ts, packages/graphic-walker/src/vis/spec/view.ts
=> fix(tooltip): display NaN on aggregated fields

packages/graphic-walker/src/components/askViz/index.tsx, packages/graphic-walker/src/computation/serverComputation.ts, packages/graphic-walker/src/dataSource/config.ts
This commit avoid showing error message when providing a mock empty source as computation function.
and fixed crash when askviz recieve a old version VisSpec struct.
=> fix: add null check & visConfig forward

packages/graphic-walker/src/utils/save.ts
Fixed the initial value of geom in visualConfig become undefined.
=> fix: geom init value

packages/graphic-walker/src/components/leafletRenderer/ChoroplethRenderer.tsx, packages/graphic-walker/src/components/leafletRenderer/POIRenderer.tsx, packages/graphic-walker/src/components/leafletRenderer/index.tsx, packages/graphic-walker/src/interfaces.ts, packages/graphic-walker/src/renderer/pureRenderer.tsx, packages/graphic-walker/src/renderer/specRenderer.tsx, packages/graphic-walker/src/utils/vegaApiExport.ts
attach IGWHandler ref with container() when using leaflet renderer
=> feat: add export container

packages/graphic-walker/src/renderer/pureRenderer.tsx
fix leaflet height when using pure renderer
=> fix: leaflet pure renderer

packages/graphic-walker/src/components/removeConfirm.tsx, packages/graphic-walker/src/components/tabs/editableTab.tsx, packages/graphic-walker/src/locales/en-US.json, packages/graphic-walker/src/locales/ja-JP.json, packages/graphic-walker/src/locales/zh-CN.json, packages/graphic-walker/src/segments/visNav.tsx, packages/graphic-walker/src/store/visualSpecStore.ts
=> Feat  delete chart

.github/workflows/auto-build.yml, packages/graphic-walker/package.json, packages/graphic-walker/src/models/field.ts, packages/graphic-walker/src/store/visualSpecStore.ts
fix bug:
when transform a dimension into measure, it does not have default aggName value -> undefined.
=> fix: analytic type transform bug

packages/graphic-walker/src/components/leafletRenderer/ChoroplethRenderer.tsx, packages/graphic-walker/src/renderer/pureRenderer.tsx, packages/graphic-walker/src/store/visualSpecStore.ts, packages/graphic-walker/src/utils/index.ts
Remove limit and sort property from PureRenderer, and read it from visualState&visualConfig.
Fixed renderer keep showing "Loading Geographic Data..." When no geoData is set.
=> Fix: pure renderer props

packages/graphic-walker/src/index.tsx, packages/graphic-walker/src/utils/workflow.ts
export a new function addFilterForQuery, to make user easier to add filter for computation.
=> feat: export function to mod filter

packages/graphic-walker/src/components/leafletRenderer/ChoroplethRenderer.tsx, packages/graphic-walker/src/components/leafletRenderer/POIRenderer.tsx, packages/graphic-walker/src/components/leafletRenderer/geojsonRenderer.tsx, packages/graphic-walker/src/components/leafletRenderer/utils.ts
resolves #186
add ChangeView component metioned in #186 ,and fixes the wrong bounds calculation.
https://github.com/Kanaries/graphic-walker/assets/15280968/f7fbccf3-ce26-41ba-8140-2efe22004552
=> fix: make map center effective

packages/graphic-walker/package.json, packages/graphic-walker/src/App.tsx, packages/graphic-walker/src/FullApp.tsx, packages/graphic-walker/src/components/askViz/index.tsx, packages/graphic-walker/src/components/codeExport/index.tsx, packages/graphic-walker/src/components/pivotTable/index.tsx, packages/graphic-walker/src/components/selectContext/index.tsx, packages/graphic-walker/src/components/tabs/editableTab.tsx, packages/graphic-walker/src/components/visualConfig/index.tsx, packages/graphic-walker/src/computation/index.ts, packages/graphic-walker/src/dataSource/dataSelection/csvData.tsx, packages/graphic-walker/src/fields/aestheticFields.tsx, packages/graphic-walker/src/fields/components.tsx, packages/graphic-walker/src/fields/encodeFields/singleEncodeEditor.tsx, packages/graphic-walker/src/fields/filterField/filterEditDialog.tsx, packages/graphic-walker/src/fields/posFields/index.tsx, packages/graphic-walker/src/index.tsx, packages/graphic-walker/src/models/visSpecHistory.ts, packages/graphic-walker/src/renderer/hooks.ts, packages/graphic-walker/src/renderer/index.tsx, packages/graphic-walker/src/renderer/specRenderer.tsx, packages/graphic-walker/src/segments/segmentNav.tsx, packages/graphic-walker/src/segments/visNav.tsx, packages/graphic-walker/src/store/dataStore.ts, packages/graphic-walker/src/store/index.tsx, packages/graphic-walker/src/store/visualSpecStore.ts, packages/graphic-walker/src/vanilla.tsx, packages/graphic-walker/src/vis/react-vega.tsx, packages/graphic-walker/src/vis/theme.ts, yarn.lock
fixes render issue when drag fields to X-axis.
=> fix: facet issue

packages/graphic-walker/src/computation/index.ts, packages/graphic-walker/src/fields/datasetFields/utils.ts, packages/graphic-walker/src/fields/filterField/filterEditDialog.tsx, packages/graphic-walker/src/fields/filterField/tabs.tsx, packages/graphic-walker/src/store/visualSpecStore.ts, packages/graphic-walker/src/utils/workflow.ts
Add support for filter with computed field.
check:
=> fix: computed field with filter

packages/graphic-walker/src/lib/gog.ts, packages/graphic-walker/src/models/visSpecHistory.ts, packages/graphic-walker/src/store/commonStore.ts, packages/graphic-walker/src/store/dataStore.ts
=> feat: add lint for grammar of graphics

packages/graphic-walker/src/dataSource/config.ts, packages/graphic-walker/src/lib/gog.ts
+ add earthquake dataset
+ force semanticType lint for geo field
=> feat: add new dataset

packages/graphic-walker/src/components/filterWalker/index.tsx, packages/graphic-walker/src/components/visualConfig/range-scale.tsx, packages/graphic-walker/src/computation/index.ts, packages/graphic-walker/src/fields/filterField/tabs.tsx, packages/graphic-walker/src/index.tsx, packages/graphic-walker/src/utils/workflow.ts
Add component to use filter outside the graphic walker.
usage: 
```
import { GraphicWalker, createFilterContext } from "@kanaries/graphic-walker";
const FilterContext = createFilterContext({
SingleSelect: (props: {
name: string;
options: string[];
value: string;
onChange?: (v: string) => void;
}) => {
// return Your select component, such as <select>
},
MultiSelect: (props: {
name: string;
options: string[];
value: string[];
onChange?: (v: string[]) => void;
}) => {
// return Your Multi select component, such as <checkbox>
},
RangeSelect: (props: {
name: string;
domain: [number, number];
value: [number, number];
onChange?: (v: [number, number]) => void;
}) => {
// return Your Range component, such as <input type="range">
},
TemporalSelect: (props: {
name: string;
domain: [number, number]; …
```
=> Feat export filter mod

packages/graphic-walker/src/App.tsx, packages/graphic-walker/src/components/dataTable/index.tsx, packages/graphic-walker/src/components/dataTable/pagination.tsx, packages/graphic-walker/src/components/dataTypeIcon.tsx, packages/graphic-walker/src/components/dropdownContext/index.tsx, packages/graphic-walker/src/components/tabs/defaultTab.tsx, packages/graphic-walker/src/dataSource/table.tsx, packages/graphic-walker/src/fields/datasetFields/dimFields.tsx, packages/graphic-walker/src/fields/datasetFields/meaFields.tsx, packages/graphic-walker/src/visualSettings/index.tsx
Previous Data Table
New Data Table
=> feat: add pagination for table

packages/graphic-walker/src/App.tsx, packages/graphic-walker/src/components/side-resize.tsx, packages/graphic-walker/src/fields/datasetFields/index.tsx, packages/graphic-walker/src/fields/encodeFields/singleEncodeEditor.tsx
Make User able to change Encoding width.
=> chore: make sidebar resizeable

packages/graphic-walker/src/fields/datasetFields/dimFields.tsx, packages/graphic-walker/src/fields/datasetFields/meaFields.tsx, packages/graphic-walker/src/fields/encodeFields/singleEncodeEditor.tsx
=> feat: field hover full name

packages/graphic-walker/src/App.tsx, packages/graphic-walker/src/components/dataBoard.tsx, packages/graphic-walker/src/components/dataTable/index.tsx, packages/graphic-walker/src/components/embedMenu.tsx, packages/graphic-walker/src/config.ts, packages/graphic-walker/src/interfaces.ts, packages/graphic-walker/src/locales/en-US.json, packages/graphic-walker/src/locales/ja-JP.json, packages/graphic-walker/src/locales/zh-CN.json, packages/graphic-walker/src/renderer/index.tsx, packages/graphic-walker/src/store/visualSpecStore.ts, packages/graphic-walker/src/utils/workflow.ts
Add a Menu Item to View all Data for a Geom in Chart.
Viewing all data with Male
Viewing all data with multi conditions
Viewing Single Data on chart
=> feat: add Geom View

packages/graphic-walker/src/Table.tsx, packages/graphic-walker/src/components/dataTable/index.tsx, packages/graphic-walker/src/components/dataTable/pagination.tsx, packages/graphic-walker/src/dataSource/datasetConfig/index.tsx
Changed the now section's color of pagination to make it more readable.
Fixed the semantic menu to the right to make the semantic type of first col is editable.
=> optimize: dataTable optimize

packages/graphic-walker/src/utils/workflow.ts
fixed when using aggeration filter with Not In rule.
=> fix: not in with aggeration filter

packages/graphic-walker/src/components/leafletRenderer/ChoroplethRenderer.tsx, packages/graphic-walker/src/components/leafletRenderer/POIRenderer.tsx, packages/graphic-walker/src/components/leafletRenderer/color.tsx, packages/graphic-walker/src/index.css, packages/graphic-walker/tailwind.config.js
Added darkmode support for Leaflet map.
=> chore: add dark mode support for map

packages/graphic-walker/src/utils/workflow.ts
remove duplicate computations in workflow.
when a chart has a same field on different encoding, such as 'x' & 'color', there will be duplicate items in workflow, which causes some no-need calculations.
e.g.
beforeWorkflow:
```
[
{
"type": "view",
"query": [
{
"op": "aggregate",
"groupBy": [
"c_5"
],
"measures": [
{
"field": "c_10",
"agg": "mean",
"asFieldKey": "c_10_mean"
},
{
"field": "c_10",
"agg": "mean",
"asFieldKey": "c_10_mean"
}
]
}
]
}
]
```
nowWorkflow:
```
[
{
"type": "view",
"query": [
{
"op": "aggregate",
"groupBy": [
"c_5"
],
"measures": [
{
"field": "c_10",
"agg": "mean",
"asFieldKey": "c_10_mean"
}
]
}
]
}
]
```
=> fix: remove duplication aggerations in workflow

packages/graphic-walker/src/App.tsx, packages/graphic-walker/src/components/askViz/index.tsx, packages/graphic-walker/src/components/errorpanel/index.tsx, packages/graphic-walker/src/interfaces.ts, packages/graphic-walker/src/locales/en-US.json, packages/graphic-walker/src/locales/ja-JP.json, packages/graphic-walker/src/locales/zh-CN.json, packages/graphic-walker/src/store/dataStore.ts, packages/graphic-walker/src/store/visualSpecStore.ts, packages/graphic-walker/src/utils/reportError.ts
add a feedback for askviz.
add error notice for askviz error.
=> feat: add feedback for askviz

packages/graphic-walker/src/index.tsx, packages/graphic-walker/src/utils/workflow.ts
add a function chartToWorkflow to get a query of a chart.
=> feat: export function chart_to_workflow

packages/graphic-walker/src/components/actionMenu/index.tsx, packages/graphic-walker/src/components/selectContext/index.tsx, packages/graphic-walker/src/fields/fieldsContext.tsx
fix the menu position when using in modal.
before( when in modal):
fixed:
=> fix: menu position in modal

packages/graphic-walker/package.json, packages/graphic-walker/src/components/errorpanel/index.tsx, yarn.lock
- fixed the menu closing issue. now you can click outside and close the menu.
- fixed when used in strict mode, the dnd cannot be performed.
- fixed the error modal's close button doesn't work.
=> fix: some ux bugs

packages/graphic-walker/src/components/leafletRenderer/ChoroplethRenderer.tsx, packages/graphic-walker/src/components/leafletRenderer/POIRenderer.tsx, packages/graphic-walker/src/components/leafletRenderer/index.tsx, packages/graphic-walker/src/components/visualConfig/index.tsx, packages/graphic-walker/src/index.css, packages/graphic-walker/src/interfaces.ts, packages/graphic-walker/src/locales/en-US.json, packages/graphic-walker/src/locales/ja-JP.json, packages/graphic-walker/src/locales/zh-CN.json
make user can custom the map tile, to use they customed map or just remove the map.
=> feat: customing map tile

packages/graphic-walker/src/components/leafletRenderer/geoConfigPanel.tsx, packages/graphic-walker/src/components/leafletRenderer/geojsonRenderer.tsx
=> fix: geoconfig panel in darkmode

packages/graphic-walker/src/fields/encodeFields/singleEncodeEditor.tsx, packages/graphic-walker/src/models/visSpecHistory.ts, packages/graphic-walker/src/store/visualSpecStore.ts
should resolves #268
1. Added all fold options when apply Measure Name field
2. Auto add "Measure Name" to Details channel(displays in tooltip) when add only Measure Value.
=> feat: fold fields optimize

packages/graphic-walker/src/models/visSpecHistory.ts
Add the filter field when applying paint field with erase.
=> feat: auto add filter field when erasing

packages/graphic-walker/src/App.tsx, packages/graphic-walker/src/components/painter/index.tsx
add darkmode support for painter
=> fix: support for painter dark mode

packages/graphic-walker/src/interfaces.ts, packages/graphic-walker/src/lib/op/fold.ts, packages/graphic-walker/src/utils/workflow.ts
this PR fixes error when using aggergated computed field with Measure Values.
1. when in aggergated chart, the aggergated computed field will show in chart.
2. when not in aggergated chart, the aggergated computed field will be ignored.
=> fix: aggergated computed field with fold

packages/graphic-walker/src/components/painter/index.tsx, packages/graphic-walker/src/interfaces.ts, packages/graphic-walker/src/lib/execExp.ts, packages/graphic-walker/src/lib/paint.ts, packages/graphic-walker/src/store/visualSpecStore.ts, packages/graphic-walker/src/utils/workflow.ts
includes multi-facet painter editing.
=> feat: painter support multi facets

packages/graphic-walker/package.json, packages/graphic-walker/src/App.tsx, packages/graphic-walker/src/Table.tsx, packages/graphic-walker/src/components/filterWalker/index.tsx, packages/graphic-walker/src/index.tsx, packages/graphic-walker/src/interfaces.ts, packages/graphic-walker/src/renderer/pureRenderer.tsx, yarn.lock
change the function into override, so there'll be a nicer error message.
=> optimize: change component props error info

packages/graphic-walker/src/lib/op/fold.ts
fix a issue made fold unusable
=> fix: fold function

packages/graphic-walker/src/components/pivotTable/index.tsx, packages/graphic-walker/src/components/pivotTable/metricTable.tsx
- Intended to solve Kanaries/pygwalker#310
@islxyqwe I have got the layout.format, but where do I need to put it into here?
=> Added code for layout formatting in table

packages/graphic-walker/src/App.tsx, packages/graphic-walker/src/Renderer.tsx, packages/graphic-walker/src/Table.tsx, packages/graphic-walker/src/components/dataTable/index.tsx, packages/graphic-walker/src/components/dataTable/profiling.tsx, packages/graphic-walker/src/components/filterWalker/index.tsx, packages/graphic-walker/src/components/modal.tsx, packages/graphic-walker/src/components/smallModal.tsx, packages/graphic-walker/src/computation/index.ts, packages/graphic-walker/src/dataSource/dataSelection/csvData.tsx, packages/graphic-walker/src/dataSource/index.tsx, packages/graphic-walker/src/interfaces.ts, packages/graphic-walker/src/renderer/pureRenderer.tsx, packages/graphic-walker/src/store/context.ts, packages/graphic-walker/src/store/theme.ts, packages/graphic-walker/src/utils/context.tsx, packages/graphic-walker/src/utils/index.ts, packages/graphic-walker/src/utils/workflow.ts, packages/graphic-walker/src/vanilla.tsx, packages/graphic-walker/src/vis/react-vega.tsx
=> feat: data profiling

packages/graphic-walker/src/components/painter/index.tsx, packages/graphic-walker/src/utils/index.ts, packages/graphic-walker/src/vis/react-vega.tsx
fixes a issue that may cause vega render loop.
=> fix: react vega unnessery renders

packages/graphic-walker/src/vis/react-vega.tsx
Resize chart immediately, instead of set it by a 'modifier' so the chart won't blink in container mode.
=> optimize: resize chart immediately

packages/graphic-walker/src/hooks/index.ts
fixed the limit setting hook caused effect loop
=> fix: limit setting

packages/graphic-walker/src/vis/react-vega.tsx, packages/graphic-walker/src/vis/theme.ts
fix the boxplot line color in darkmode.
=> fix: boxplot line color in darkmode

packages/graphic-walker/src/interfaces.ts, packages/graphic-walker/src/vis/theme.ts
Add the streamlit theme for Graphic walker.
usage: set the prop themeKey="streamlit"
```
<GraphicWalker {...props} themeKey="streamlit" />
```
=> feat: add streamlit theme

packages/graphic-walker/src/components/leafletRenderer/ChoroplethRenderer.tsx, packages/graphic-walker/src/components/leafletRenderer/POIRenderer.tsx
This PR sets leaflet map to use canvas to improve performance.
=> fix: leaflet use canvas

packages/graphic-walker/package.json, packages/graphic-walker/src/components/painter/index.tsx, yarn.lock
This PR added the webgl-renderer to improve the painter module performance.
=> fix: optimize painter

packages/graphic-walker/src/components/painter/index.tsx, packages/graphic-walker/src/utils/colors.ts
fixed the painter background color in light mode.
=> fix: painter webgl renderer background color

packages/graphic-walker/src/lib/gog.ts, packages/graphic-walker/src/models/visSpecHistory.ts, packages/graphic-walker/src/utils/index.ts, packages/graphic-walker/src/vis/spec/mark.ts
Pivot table / tables should not have limit of variables.
=> fix: pivot table var number limit

packages/graphic-walker/package.json, packages/graphic-walker/src/App.tsx, packages/graphic-walker/src/components/chat/index.tsx, packages/graphic-walker/src/components/ui/card.tsx, packages/graphic-walker/src/components/ui/collapsible.tsx, packages/graphic-walker/src/components/ui/textarea.tsx, packages/graphic-walker/src/fields/filterField/filterPill.tsx, packages/graphic-walker/src/fields/filterField/simple.tsx, packages/graphic-walker/src/fields/filterField/slider.tsx, packages/graphic-walker/src/fields/filterField/tabs.tsx, packages/graphic-walker/src/interfaces.ts, packages/graphic-walker/src/lib/filter.ts, packages/graphic-walker/src/lib/vl2gw.ts, packages/graphic-walker/src/locales/en-US.json, packages/graphic-walker/src/locales/ja-JP.json, packages/graphic-walker/src/locales/zh-CN.json, packages/graphic-walker/src/models/chat.ts, packages/graphic-walker/src/models/visSpec.ts, packages/graphic-walker/src/models/visSpecHistory.ts, packages/graphic-walker/src/renderer/index.tsx, packages/graphic-walker/src/store/visualSpecStore.ts, packages/graphic-walker/src/utils/workflow.ts, packages/graphic-walker/tsconfig.json, yarn.lock
Make use can chat in graphic walker.
It's designed to be used in pygwalker and etc.
=> feat: chat enhance

packages/graphic-walker/src/components/painter/components.tsx, packages/graphic-walker/src/components/visualConfig/index.tsx, packages/graphic-walker/src/lib/op/offset.ts, packages/graphic-walker/src/renderer/specRenderer.tsx, packages/graphic-walker/src/vis/spec/encode.ts, packages/graphic-walker/src/vis/spec/view.ts
1.fixed the date shown in vega chart with displayOffset.
[bug reproducing demo](https://github.com/Kanaries/graphic-walker/files/14634452/graphic-walker-notebook.46.json)
2.add a error boundary to react color for some time that react-color explodes.
3.add background for exporting the chart image.
This PR fixes bugs above.
=> fix: chart bugs of timeoffset, react-color, background

packages/graphic-walker/src/App.tsx, packages/graphic-walker/src/components/computedField/index.tsx, packages/graphic-walker/src/components/highlightField.tsx, packages/graphic-walker/src/components/renameField/index.tsx, packages/graphic-walker/src/fields/datasetFields/utils.ts, packages/graphic-walker/src/models/visSpecHistory.ts, packages/graphic-walker/src/store/visualSpecStore.ts
This PR add a panel to edit field name in chart, and replace all names in charts and computed fields.
=> feat: add rename feature for fields

packages/graphic-walker/src/App.tsx, packages/graphic-walker/src/components/actionMenu/index.tsx, packages/graphic-walker/src/components/chat/index.tsx, packages/graphic-walker/src/components/painter/index.tsx, packages/graphic-walker/src/components/pivotTable/index.tsx, packages/graphic-walker/src/components/toolbar/index.tsx, packages/graphic-walker/src/components/ui/tabs.tsx, packages/graphic-walker/src/dataSource/index.tsx, packages/graphic-walker/src/fields/components.tsx, packages/graphic-walker/src/fields/datasetFields/dimFields.tsx, packages/graphic-walker/src/fields/datasetFields/index.tsx, packages/graphic-walker/src/fields/datasetFields/meaFields.tsx, packages/graphic-walker/src/fields/encodeFields/multiEncodeEditor.tsx, packages/graphic-walker/src/fields/encodeFields/singleEncodeEditor.tsx, packages/graphic-walker/src/fields/filterField/filterPill.tsx, packages/graphic-walker/src/fields/filterField/index.tsx, packages/graphic-walker/src/fields/obComponents/obPill.tsx, packages/graphic-walker/src/renderer/index.tsx, packages/graphic-walker/src/renderer/pureRenderer.tsx, packages/graphic-walker/src/renderer/specRenderer.tsx, packages/graphic-walker/src/vis/react-vega.tsx
This PR fixed bugs below:
1. sometimes, cannot drag items from dimension fields into measure fields, or reverse.
2. sometimes, use tab to switch between windows, make the graphic walker change tab automaticly.
3. in mobile mode, the toolbar is not usable.
4. in device with touchscreen, the drag feature is broken.
=> fix: drag issues and tab issues

packages/graphic-walker/package.json
fixed the filename in package.json to resolve a issue with importing graphic-walker as a require.
=> fix: file of package.json

packages/graphic-walker/src/fields/components.tsx, packages/graphic-walker/src/fields/datasetFields/index.tsx, packages/graphic-walker/src/fields/fieldsContext.tsx
fixed the scroll issue when measures has a large amount of fields.
=> fix: scroll issue

packages/graphic-walker/src/components/selectContext/index.tsx
Fixed the display issue in #363.
=> fix: fold menu

packages/graphic-walker/src/components/filterContext/index.tsx, packages/graphic-walker/src/index.tsx, packages/playground/src/examples/nav.tsx, packages/playground/src/examples/pages/filterContext.stories.tsx, packages/playground/src/examples/pages/filterContext.tsx
Add a new set of components to make user make dashboard page easier.
See the example at `packages/playground/src/examples/pages/filterContext.stories.tsx`.
usage: 
```
<ComputationProvider data={dataSource}>
<div className="flex flex-col gap-2">
<div className="w-full flex justify-end">
<div className="w-[300px]">
<SelectFilter fid="parental level of education" name="parental level of education" />
</div>
</div>
<Chart chart={spec[0] as IChart} appearance={theme} />
<Chart chart={spec2[0] as IChart} appearance={theme} />
</div>
</ComputationProvider>
```
=> feat: new filter context

packages/duckdb-wasm-computation/package.json, packages/graphic-walker/src/components/painter/index.tsx, yarn.lock
Fixed the crash when editing a single paint facet which is generated by painting on a aggergated chart.
=> fix: cannot edit single facet with agg

packages/graphic-walker/src/components/painter/index.tsx, packages/graphic-walker/src/lib/paint.ts
fixed the issue when using paint with binned field.
=> fix: bin paint

packages/playground/gallery.html, packages/playground/src/gallery/components/ErrorPage.tsx, packages/playground/src/gallery/components/Example.tsx, packages/playground/src/gallery/components/GalleryGroup.tsx, packages/playground/src/gallery/components/ThemeToggle.tsx, packages/playground/src/gallery/context.ts, packages/playground/src/gallery/index.css, packages/playground/src/gallery/index.tsx, packages/playground/src/gallery/layout.tsx, packages/playground/src/gallery/pages.tsx, packages/playground/src/gallery/resources.ts, packages/playground/src/gallery/util.ts, packages/playground/vercel.json, packages/playground/vite.config.ts
Added a gallery page to the playground.
=> feat: add gallery in playground

packages/graphic-walker/src/dataSource/dataSelection/config.ts
This PR added more charset options to support more encodings of files.
=> feat: update charset options

packages/graphic-walker/src/components/visualConfig/color-picker.tsx, packages/graphic-walker/src/components/visualConfig/colorScheme.tsx, packages/graphic-walker/src/components/visualConfig/index.tsx
Change the background config, using colorPicker for modification.
=> chore: background picker input

packages/graphic-walker/src/App.tsx, packages/graphic-walker/src/Renderer.tsx, packages/graphic-walker/src/Table.tsx, packages/graphic-walker/src/components/visualConfig/index.tsx, packages/graphic-walker/src/dataSource/index.tsx, packages/graphic-walker/src/locales/en-US.json, packages/graphic-walker/src/locales/ja-JP.json, packages/graphic-walker/src/locales/zh-CN.json, packages/graphic-walker/src/renderer/pureRenderer.tsx, packages/graphic-walker/src/store/theme.ts
- allow changing theme via context
- expose theme select in visual config panel
- update locale files for new theme label
- propagate theme selection through app and renderer components
- `npm run build`
=> Add theme selection to visual config

packages/graphic-walker/index.html, packages/graphic-walker/src/App.tsx, packages/graphic-walker/src/fields/aestheticFields.tsx, packages/graphic-walker/src/fields/datasetFields/index.tsx, packages/graphic-walker/src/fields/fieldsContext.tsx, packages/graphic-walker/src/main.tsx, packages/graphic-walker/src/root.tsx, packages/playground/index.html, packages/playground/src/main.tsx
This PR removes the fixed height behavior for the graphic walker component.
BREAKING CHANGE: after this PR, user should control their component height by passing height or classname, so the component won't grow infinitely when field num grows.
=> chore:improve height style

packages/graphic-walker/src/fields/filterField/tabs.tsx
added the functionilty to select all with keyword searched.
=> feat: select all when have keyword

packages/graphic-walker/src/lib/vega.ts, packages/graphic-walker/src/store/index.tsx, packages/graphic-walker/src/vis/react-vega.tsx
fix the warning in the boxplot:
```
WARN Selection not supported for boxplot yet.
Error: Unrecognized signal name: "geom"
```
=> fix: warning in boxplot

.github/workflows/auto-build.yml, packages/graphic-walker/src/App.tsx, packages/graphic-walker/src/components/dataBoard.tsx, packages/graphic-walker/src/dataSource/datasetConfig/index.tsx, packages/graphic-walker/src/interfaces.ts, packages/playground/src/examples/nav.tsx, packages/playground/src/examples/pages/hideProfiling.stories.tsx, packages/playground/src/examples/pages/hideProfiling.tsx
added the hideProfiling option for not only Tablewalker, but also GraphicWalker.
=> chore: add props of hide profiling in the main component
